# Site settings
title: Marlboro
email: marlboro027@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marlboro029.github.io" # the base hostname & protocol for your site
twitter_username: marlboro027@foxmail.com
github_username: marlboro029

# Build settings
markdown: kramdown

highlighter: pygments
github: [Repository metadata]


safe: true
lsi: false